README.md
app/javascript/controllers/game_controller.js
app/models/word.rb
app/services/games/score_calculator.rb
app/services/games/session_manager.rb
lib/tasks/import_words.rake
spec/services/games/session_manager_spec.rb

「回答時間のボーナス」という概念を削除しました。これは元々の要件にはなかった機能です。
具体的には以下の変更を行いました：
1. スコア計算からタイムボーナスの乗算処理を削除
2. ゲームセッションマネージャーからタイムボーナス情報の返却処理を削除
3. フロントエンドのタイムボーナス表示部分を削除
4. テストコードからタイムボーナス関連部分を修正

回答時間のボーナス概念を削除

---

lib/tasks/import_words.rake

- メソッドで単語を抽出する際に、単語の先頭または最後が数字の場合はスキップするように修正
- メソッドでも単語の先頭または最後が数字かどうかをチェックし、数字で始まるか終わる単語はスキップするように修正
- これらの変更により、数字で始まるまたは終わる単語（例：1test、test2など）がゲームで使用されなくなります。

単語の先頭または最後が数字の単語を登録しないように修正

---

README.md
db/seeds.rb

- db/seeds.rb を修正して、 で初期データを投入できるようにしました
- README.md の初期データ投入手順を更新しました
このPRでは、以下の変更を行いました：
1. db/seeds.rbに以下のRakeタスクを呼び出すコードを追加
- words:import_keywords
- words:import_from_doctree
- words:update_descriptions
2. README.mdのセットアップ手順を更新し、複数のRakeタスクの代わりに  コマンド一つで初期データを投入できるようにしました
これにより、初期セットアップの手順がシンプルになり、ユーザー体験が向上します。

初期データ投入をrake db:seedで実行できるように修正

---

app/javascript/controllers/game_controller.js

無効な単語入力時にタイマーがリセットされる問題を修正しました。これにより、ルール違反の単語を連続入力して時間切れを回避できる問題が解決されました。

無効な単語入力時にタイマーがリセットされる問題を修正

---

.github/workflows/deploy.yml

- GitHub Actions OIDCの認証方法を修正
- 非推奨または存在しないアクションを削除
- アクションを直接使用するように変更
- デバッグ情報を追加して認証状態を確認できるように改善
GitHub Actionsのデプロイワークフローで「Error: Missing download info for actions/id-token@v2」というエラーが発生していました。このエラーはアクションが存在しないか非推奨になったことが原因です。
最新のOIDC認証方法では、アクションを使用せず、直接アクションを使用することが推奨されています。このアクションは内部でOIDCトークンを取得し、AWSの認証を行います。
また、デバッグ用のステップを追加して、AWS認証情報が正常に設定されたことを確認できるようにしました。

GitHub Actions OIDCの認証方法を修正

---

.github/workflows/deploy.yml
docs/ci_cd.md

- GitHub ActionsのデプロイワークフローでECSタスク定義のデプロイ時に発生するエラーを修正
- タスク定義から不要なプロパティ（registeredAt, registeredBy等）を削除するステップを追加
- CI/CDドキュメントのトラブルシューティングセクションに関連情報を追加
ECSタスク定義をデプロイする際に、コマンドで取得したタスク定義に、新しいタスク定義を登録する際には不要（または許可されていない）プロパティが含まれていることが原因でエラーが発生していました。この修正では、タスク定義から不要なプロパティを削除するステップをワークフローに追加しています。

Fix ECS task definition deployment error

---

app/controllers/api/games_controller.rb
app/javascript/controllers/game_controller.js
app/services/games/session_manager.rb

- ゲーム開始ボタン押下時に発生する422エラーの問題を修正
- サーバー側でのエラーハンドリングを改善し、JSONレスポンスを返すように変更
- フロントエンド側でのエラーハンドリングを改善し、詳細なエラーメッセージを表示するように変更
トップ画面で「ゲーム開始」ボタンを押下すると422エラーが発生し、HTMLが返されていた問題を修正しました。サーバー側でエラーが発生した場合でもJSONレスポンスを返すようにし、フロントエンド側でそのエラーメッセージを適切に表示するようにしました。
具体的な変更点：
1. アクションに例外処理を追加
2. メソッドに例外処理を追加
3. フロントエンド側の `game_controller.js` のエラーハンドリングを改善

ゲーム開始時のエラーハンドリングを改善

---

app/controllers/api/games_controller.rb

- APIコントローラーでCSRF検証をJSONリクエストの場合のみスキップするように修正
ゲーム開始ボタンを押したときに422 Unprocessable Entityエラーが発生する問題を修正しました。
問題の原因は、APIコントローラーでのCSRF（クロスサイトリクエストフォージェリ）トークン検証の設定にありました。元のコードでは、リクエストがJSONフォーマットの場合のみCSRF検証をスキップする設定になっていましたが、何らかの理由でリクエストがJSONとして正しく認識されていませんでした。
修正内容：
- ファイルを編集し、JSONリクエストの場合のみCSRF検証をスキップするように変更しました。
- Content-Typeヘッダーが「application/json」を含む場合もCSRF検証をスキップするようにしました。
これにより、セキュリティを維持しつつ、APIリクエストが正常に処理されるようになります。

ゲーム開始時の422エラーを修正

---

app/javascript/controllers/game_controller.js

- セッションIDをオブジェクトから文字列に変換するよう修正
- URLパラメータにセッションIDを追加する際にencodeURIComponentを使用
- タイムアウト処理でも同様の修正を適用
ゲーム開始後に単語を送信すると「ゲームセッションが見つかりません」というエラーが発生していた問題を修正しました。
原因はセッションIDがJavaScriptオブジェクトとして扱われ、URLパラメータに`[object Object]`という文字列として含まれていたことでした。これにより、バックエンドでセッションを復元できず、エラーが発生していました。
修正内容：
1. セッションIDを保存する際に`String()`を使用して確実に文字列に変換
2. URLパラメータとして追加する際に`encodeURIComponent()`でエンコード
3. タイムアウト処理でも同様の修正を適用"

セッションIDの処理を修正し、ゲーム中の単語送信エラーを解消

---

app/controllers/api/games_controller.rb
app/javascript/controllers/game_controller.js

- バックエンド側でセッションIDを明示的に文字列に変換
- セッションIDの型をログに出力して確認できるように改善
- フロントエンド側でセッションIDがオブジェクトとして受信された場合の処理を追加
- オブジェクトの場合はJSONに変換して文字列化する処理を実装
- より詳細なログ出力を追加
前回の修正でセッションIDを文字列として扱うようにしましたが、デプロイ後も同様のエラーが発生していました。今回の修正では、セッションIDの処理をさらに強化し、オブジェクト型の場合の対応を追加しました。
バックエンド側では、セッションIDを明示的に文字列に変換し、型情報をログに出力するようにしました。フロントエンド側では、セッションIDがオブジェクトとして受信された場合に、JSONに変換して文字列化する処理を追加しました。
これらの修正により、セッションIDが確実に文字列として扱われるようになり、エラーが解消されることが期待されます。

セッションID処理を強化し、オブジェクト型の場合の対応を追加

---

app/controllers/api/games_controller.rb
app/javascript/controllers/game_controller.js

- セッションIDをURLパラメータではなく、ヘッダー（X-Session-ID）に含めるように変更
- バックエンド側でヘッダーまたはURLパラメータからセッションIDを取得するように対応
- セッションIDの検索処理を改善（完全一致で見つからない場合は部分一致で検索）
- より詳細なログ出力を追加して、問題の特定を容易に
- セッションデータの解析処理を改善して、様々な型に対応
前回の修正でセッションIDを文字列として扱うようにしましたが、デプロイ後も同様のエラーが発生していました。今回の修正では、セッションIDの送信方法を根本的に見直し、URLパラメータではなくHTTPヘッダーを使用する方式に変更しました。
これにより、URLの長さ制限やエンコーディングの問題を回避し、より安定したセッション管理が可能になります。また、セッションIDの検索処理も改善し、完全一致で見つからない場合は部分一致で検索するなど、柔軟な対応を行うようにしました。
これらの修正により、「ゲームセッションが見つかりません」というエラーが解消されることが期待されます。

セッションID処理を大幅に改善し、ヘッダーベースの方式に変更

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
terraform/alb.tf
terraform/outputs.tf
terraform/route53.tf
terraform/variables.tf

- Route 53の設定を追加（shiritoruby.link ドメイン）
- ACM証明書の設定を追加
- ALBのHTTPSリスナー設定を修正
- 関連する変数と出力を追加
- terraform/route53.tf: Route 53のホストゾーン、DNSレコード、ACM証明書の検証設定
- terraform/alb.tf: HTTPSリスナーの設定を修正
- terraform/variables.tf: ドメイン関連の変数を追加
- terraform/outputs.tf: Route 53関連の出力を追加
DNSの伝播が完了するまで、最大48時間かかる場合があります。以下の手順で確認できます：
1.  `dig NS shiritoruby.link` コマンドを実行して、ネームサーバーが以下に変わったことを確認：
- ns-1131.awsdns-13.org
- ns-172.awsdns-21.com
- ns-2004.awsdns-58.co.uk
- ns-746.awsdns-29.net
2. DNSの伝播が完了したら、ACM証明書の検証も自動的に完了します：
```
aws acm describe-certificate --certificate-arn $(aws acm list-certificates --query "CertificateSummaryList[?DomainName=='shiritoruby.link'].CertificateArn" --output text) --query "Certificate.Status"
```
結果が「ISSUED」になったら、証明書の検証が完了しています。
3. 証明書の検証が完了したら、以下のURLでアプリケーションにアクセスできるようになります：
- …

ドメイン設定の追加（shiritoruby.link）

---

terraform/ecs.tf
terraform/secrets.tf

- シークレットの名前を変更して削除予定のシークレットとの競合を回避
- ECSタスク定義のリビジョン番号の問題を解決
1. Secrets Managerのシークレットが削除予定であるため、新しいシークレットを作成できない問題を解決
- シークレットの名前を変更（`RAILS_MASTER_KEY` → `RAILS_MASTER_KEY_NEW`、`DATABASE_URL` → `DATABASE_URL_NEW`）
2. ECSサービスのタスク定義のリビジョン番号の問題を解決
- リビジョン番号を指定する代わりに、最新のリビジョンを使用するように修正
これらの修正により、インフラストラクチャの正常なデプロイが可能になり、ドメイン「shiritoruby.link」でアプリケーションにアクセスできるようになりました。

インフラストラクチャの設定を修正

---

app/controllers/api/games_controller.rb
app/services/games/session_manager.rb
app/services/games/session_service.rb

`:SlackChannels`を実行すると以下のエラーが発生していました：
Error executing vim.schedule lua callback: ...al/share/nvim/lazy/neo-slack.nvim/lua/neo-slack/init.lua:246: attempt to index upvalue 'ui' (a boolean value)
`lua/neo-slack/ui.lua`ファイルの最後に`return M`が欠けていたため、モジュールがテーブルを返していませんでした。そのため、`init.lua`で`ui`変数がブール値として扱われ、`ui.show_channels(channels)`でエラーが発生していました。
`ui.lua`ファイルの最後に`return M`を追加し、モジュールが正しくテーブルを返すようにしました。これにより、`ui.show_channels(channels)`が正常に動作するようになります。

Fix: UIモジュールがテーブルを返すように修正

---

config/application.rb

- アプリケーションのタイムゾーンを日本時間（JST）に設定
- データベースの時間はUTCのまま（Railsのベストプラクティス）
- にタイムゾーン設定を追加
- でアプリケーションのタイムゾーンを日本時間に設定
- でデータベースの時間はUTCのまま保持
- テストとRubocopが全て通過することを確認済み

アプリケーションのタイムゾーンを日本時間（JST）に設定

---

terraform/ecs.tf
terraform/iam.tf

- 本番環境のRailsコンソールにアクセスするためにECS Execを有効化
- ECSタスクロールとECS Exec用のIAMポリシーを追加
- ECSサービスでExecute Commandを有効化
本番環境のRailsコンソールにアクセスするために、AWS ECS Execを有効にしました。これにより、以下のコマンドで本番環境のコンソールに安全にアクセスできるようになります（zsh対応）：
```bash
curl 'https://s3.amazonaws.com/session-manager-downloads/plugin/latest/mac/sessionmanager-bundle.zip' -o 'sessionmanager-bundle.zip'
unzip sessionmanager-bundle.zip
sudo ./sessionmanager-bundle/install -i /usr/local/sessionmanagerplugin -b /usr/local/bin/session-manager-plugin
AWS_PROFILE=shiritoruby aws ecs list-tasks --cluster shiritoruby-cluster
TASK_ID=0266ec60bbdd4c86bb9b0f6ad2016af3
AWS_PROFILE=shiritoruby aws ecs execute-command --cluster shiritoruby-cluster --task  --container shiritoruby --interactive --command '/bin/bash'
cd /rails
bin/rails console
```

本番環境のコンソールアクセスのためにECS Execを有効化

---

terraform/iam.tf

- terraform/iam.tfファイルのecs_exec_policyリソースに`var.use_existing_infrastructure`変数を使用した条件を追加
- ポリシーアタッチメントにも同様の条件を追加
既存のIAMポリシー「shiritoruby-ecs-exec-policy」が既に存在していた場合に発生する重複エラーを修正しました。`var.use_existing_infrastructure`変数を使用して、既存のインフラを使用する場合は新しいポリシーを作成しないようにしました。これにより、Terraformの実行が正常に完了し、インフラストラクチャが正しく構築されるようになりました。

Terraformのecs_exec_policyリソースに条件を追加し重複エラーを修正

---

.rubocop.yml
app/assets/stylesheets/words.css
app/controllers/words_controller.rb
app/views/games/index.html.erb
app/views/games/rankings.html.erb
app/views/words/index.html.erb
config/routes.rb
spec/controllers/words_controller_spec.rb
spec/system/words_spec.rb

- 単語管理ページ（/words）を追加
- 登録済み単語リストをCSVファイルでダウンロードする機能を実装
- CSVファイルをアップロードして単語を一括登録する機能を実装
- ゲーム画面とランキング画面に単語管理ページへのリンクを追加
- WordsControllerを作成し、index, download, uploadアクションを実装
- 単語管理ページのビューとスタイルを作成
- コントローラーテストとシステムテストを実装

単語管理ページの追加

---

terraform/github.tf

- GitHub Actionsが使用するIAMロール（github-actions-role）に、Terraformでインフラを作成するための必要な権限を追加
- 既存のECRとECSの権限に、リポジトリとクラスター作成権限を追加
- 新しいIAMポリシー（github-actions-terraform-policy）を作成し、以下の権限を追加:
- ACM（証明書管理）の権限
- CloudWatch Logsの権限
- IAM（ロールとポリシー作成）の権限
- Route53（DNSゾーン管理）の権限
- Secrets Manager（シークレット管理）の権限
- EC2（VPC、サブネット、セキュリティグループなど）の権限
- Elastic Load Balancingの権限
- RDS（データベース）の権限
GitHub Actionsの`Terraform Apply`ステップで、権限不足によるエラーが発生していました。このPRでは、必要な権限をIAMロールに追加することで、Terraformが正常にAWSリソースを作成できるようにしています。

GitHub Actionsロールに必要な権限を追加

---

app/controllers/words_controller.rb
app/javascript/controllers/bulk_delete_controller.js
app/views/words/index.html.erb
config/routes.rb
spec/controllers/words_controller_spec.rb
spec/system/words_spec.rb

- 単語管理ページに複数選択・一括削除機能を追加
- 単語一覧に各行のチェックボックスを追加
- 全選択チェックボックスを追加
- 選択した単語を一括削除するボタンを追加
- 一括削除処理を行うアクションを追加
- JavaScriptで選択状態を管理
- コントローラーテストとシステムテストを追加

単語管理ページに複数選択・一括削除機能を追加

---

app/assets/stylesheets/game.css
app/controllers/api/games_controller.rb
app/javascript/controllers/game_controller.js
spec/system/game_spec.rb

- ゲーム終了画面に表示される単語一覧に「説明」カラムを追加
- APIレスポンスに単語の説明を含めるように修正
- 単語一覧のレイアウトを改善（テーブル形式に変更）
- レスポンシブ対応を強化
1. `Api::GamesController`の修正
- `timeout`アクションと`submit_word`アクションに単語の説明を含めるように修正
- `get_words_with_descriptions`メソッドを追加して、単語とその説明を取得
2. `game_controller.js`の`handleGameOver`メソッドの修正
- テーブルヘッダーを追加
- APIから返された`words_with_descriptions`を使用して単語リストを生成
- 後方互換性のために、`words_with_descriptions`がない場合は従来の方法で単語リストを生成
3. CSSの追加
- 単語一覧のヘッダーのスタイル
- 各カラム（ターン、単語、プレイヤー、説明）のスタイル
- レスポンシブ対応（スマホ表示時のレイアウト調整）
4. テストの追加
- ゲーム終了画面で単語の説明が表示されることをテスト

ゲーム終了画面の単語一覧に説明カラムを追加

---

terraform/github.tf
terraform/outputs.tf

- GitHub Actionsが使用するIAMロールに必要な権限を追加
- 既存インフラを使用するように設定
- 既存リソースの再作成を防ぐための条件を追加
1. **IAMロールの権限不足**: GitHub Actionsが使用するIAMロールに必要な権限が不足していました
2. **既存リソースの再作成**: 既に存在するリソースを再作成しようとして競合が発生していました
以下の対応を行いました：
1. **IAMロールに必要な権限を追加**
- GitHub Actionsが使用するIAMロール（github-actions-role）に以下の権限を追加：
- `acm:ListTagsForCertificate`
- `route53:ChangeTagsForResource`
- `route53:GetChange`
- `ec2:ModifyVpcAttribute`
- `ec2:DescribeVpcAttribute`
2. **既存インフラを使用するように設定**
- `terraform.tfvars`ファイルで`use_existing_infrastructure = true`に設定
- GitHub Actionsのワークフローファイルに`-var="use_existing_infrastructure=true"`を追加
3. **リソース作成条件の追加**
以下のリソースに`count = var.use_existing_infrastructure ? 0 : 1`の条件を追加：
- Route53関連リソース（ホストゾーン、レコード、ACM証明書検証）
- ACM証明書
- ECRリポジトリ
- ECSクラスター
- CloudWatch Logsロググループ
- IAM OIDCプロバイダー
- …

Terraformインフラストラクチャの修正

---

terraform/outputs.tf

- 既存インフラ使用時の出力値を修正
`use_existing_infrastructure = true`を設定している場合、`aws_iam_role.github_actions`リソースが作成されないため、`outputs.tf`ファイルの以下の参照でエラーが発生していました：
```terraform
value = aws_iam_role.github_actions[0].arn
```
出力値に条件分岐を追加して、`use_existing_infrastructure = true`の場合は別の値を返すように修正しました：
```terraform
value = var.use_existing_infrastructure ? "Using existing GitHub Actions role" : aws_iam_role.github_actions[0].arn
```
これにより、既存インフラを使用する場合でもエラーが発生しなくなります。

既存インフラ使用時の出力値を修正
